services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${SERVER_TARGET:-developer}
      args:
        DEVELOPER_USER: 'ernestosr'
    volumes:
      - "./docker/app/conf/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini"
      - "./:/app"
    environment:
      APP_ENV: dev
      PHP_IDE_CONFIG: "serverName=localhost"
      PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE:-debug}
      PHP_XDEBUG_START_WITH_REQUEST: ${PHP_XDEBUG_START_WITH_REQUEST:-yes}
      PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT:-9000}
      PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST:-host.docker.internal}

  php:
    image: php:fpm-alpine
    volumes:
      - "./docker/http/html:/var/www/html"

  http:
    build:
      context: .
      dockerfile: docker/http/Dockerfile
    image: nginx:stable-alpine
    depends_on:
      - php
    volumes:
      - "./docker/http/html:/var/www/html"
